# Generated by Django 4.2.24 on 2025-09-16 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('acdc_email', models.EmailField(max_length=254, unique=True)),
                ('personal_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('employee_id', models.CharField(max_length=20, unique=True)),
                ('department', models.CharField(choices=[('Engineering', 'Engineering'), ('Product Management', 'Product Management'), ('Design', 'Design'), ('Sales', 'Sales'), ('Marketing', 'Marketing'), ('Executive', 'Executive'), ('Human Resources', 'Human Resources'), ('Finance', 'Finance')], max_length=50)),
                ('subteam', models.CharField(blank=True, max_length=100)),
                ('position', models.CharField(max_length=150)),
                ('role', models.CharField(choices=[('Member', 'Member'), ('Director', 'Director'), ('Admin', 'Admin')], default='Member', max_length=20)),
                ('status', models.CharField(choices=[('employee', 'Employee'), ('on_leave', 'On leave'), ('inactive', 'Inactive')], default='employee', max_length=20)),
                ('timezone', models.CharField(blank=True, max_length=100)),
                ('time_commitment', models.CharField(blank=True, max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('location', models.CharField(choices=[('New York City', 'New York City'), ('San Francisco', 'San Francisco'), ('Remote', 'Remote'), ('Boston', 'Boston'), ('Chicago', 'Chicago'), ('Austin', 'Austin')], max_length=50)),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('skills', models.TextField(blank=True, help_text='Comma-separated list: React, Python, Django')),
                ('bio', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reports_to', models.ForeignKey(blank=True, help_text='Manager/Supervisor', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_reports', to='people.person')),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
                'indexes': [models.Index(fields=['employee_id'], name='people_pers_employe_e30582_idx'), models.Index(fields=['acdc_email'], name='people_pers_acdc_em_88f434_idx'), models.Index(fields=['department'], name='people_pers_departm_0bdefc_idx')],
            },
        ),
    ]
