# Generated by Django 5.2.6 on 2025-09-16 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['full_name']},
        ),
        migrations.RemoveIndex(
            model_name='person',
            name='people_pers_employe_e30582_idx',
        ),
        migrations.RemoveIndex(
            model_name='person',
            name='people_pers_acdc_em_88f434_idx',
        ),
        migrations.RemoveIndex(
            model_name='person',
            name='people_pers_departm_0bdefc_idx',
        ),
        migrations.RemoveField(
            model_name='person',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='person',
            name='employee_id',
        ),
        migrations.RemoveField(
            model_name='person',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='person',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='person',
            name='location',
        ),
        migrations.RemoveField(
            model_name='person',
            name='reports_to',
        ),
        migrations.RemoveField(
            model_name='person',
            name='role',
        ),
        migrations.RemoveField(
            model_name='person',
            name='salary',
        ),
        migrations.RemoveField(
            model_name='person',
            name='skills',
        ),
        migrations.AddField(
            model_name='person',
            name='full_name',
            field=models.TextField(default='', help_text='Full name of the person'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='acdc_email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='department',
            field=models.TextField(choices=[('Engineering', 'Engineering'), ('Product Management', 'Product Management'), ('Design', 'Design'), ('Sales', 'Sales'), ('Marketing', 'Marketing'), ('Executive', 'Executive'), ('Human Resources', 'Human Resources'), ('Finance', 'Finance')]),
        ),
        migrations.AlterField(
            model_name='person',
            name='personal_email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='position',
            field=models.TextField(choices=[('Volunteer', 'Volunteer'), ('Director', 'Director'), ('Admin', 'Admin')]),
        ),
        migrations.AlterField(
            model_name='person',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('on_leave', 'On Leave')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='person',
            name='subteam',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='time_commitment',
            field=models.SmallIntegerField(blank=True, help_text='Time commitment in hours (0-80)', null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='timezone',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['status'], name='people_status_175f4e_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['department', 'subteam'], name='people_departm_075019_idx'),
        ),
        migrations.AlterModelTable(
            name='person',
            table='people',
        ),
    ]
